# For demonstration purposes, not recommneded as it is in real projects!
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accessing-files.fullname" . }}
type: Opaque
data:
{{ (.Files.Glob "files/*.properties").AsSecrets | indent 4 }}
