# I am a YAML comment
{{/* I am a GO comment, and I will NOT remain. */}}

{{- /* I am a GO comment, and I will NOT remain. */ -}}

test: {{ .Values.test }}

# lower "Hello World" to "hello world" 
title: {{ lower .Values.title }}

# replace "Hello World" to "Hello-World" 
newtitle1: {{ replace " " "-" .Values.title }} 

# lower replace  "Hello World" to "hello-world" 
newtitle2: {{ lower (replace " " "-" .Values.title) }}

#  replace | lower  "Hello World" to "hello-world" 
newtitle3: {{ replace " " "-" .Values.title | lower }}

#  replace | lower  "Hello World" to "hello-world" 
newtitle4: {{ lower .Values.title | replace " " "-" }}

labels:
    {{/* The app label comes from the Release. */}}
    app: {{ .Values.labels.app }}
    {{/* The chart label comes from the Chart information. */}}
    chart: {{ .Chart.Name }}
{{- /* <function name> <arg1> <arg2> */ -}}


    {{ if eq .Values.environment "production" }}
    environment: production
    build: stable
    public-ingress: true
    {{ else if eq .Values.environment "staging" }}
    environment: staging
    build: stag
    public-ingress: false
    {{ else }}
    environment: dev
    build: alpha
    public-ingress: false
    {{ end }}