# Generated by Django 5.1.1 on 2024-10-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_test',
            new_name='review_text',
        ),
    ]
