apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "templating-deep-dive.fullname" . }}
  labels: {{ include "templating-deep-dive.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ if eq .Values.environment "production" -}} 2 {{- else -}} 1 {{- end }}
  selector:
    matchLabels: {{ include "templating-deep-dive.selectorLabels" . | nindent 6 }}
spec:
  template:
    metadata:
      labels: {{ include "templating-deep-dive.selectorLabels" . | nindent 8 }}
  spec: 
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"          
          {{- if .Values.services | default dict | len }}
          ports:
            - containerPort: {{ .Values.containerPorts.http }}
          {{- end }}
